# Generated by Django 2.1 on 2018-11-04 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('partysize', models.IntegerField()),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('status', models.BooleanField(choices=[(True, 'Waiting'), (False, 'Seated')])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('restaurant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
